name: CI pipeline for the solar-system app
on: push

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        env:
            MONGO_URI: ${{ vars.MONGO_URI }}
            MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js Environment
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install Dependincies
              run: npm install

            - name: Run Unit Testing
              run: npm test

              