name: Destroy created infra using Terrafor
on: workflow_dispatch
jobs:
    destroy:
        name: destroy infra
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./terraform
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v5.1.1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ vars.REGION }}

            - name: HashiCorp - Setup Terraform
              uses: hashicorp/setup-terraform@v3.1.2

            - name: Terraform init
              run: terraform init
            
            - name: Download a Build Artifact
              uses: actions/download-artifact@v6.0.0
              with:
                name: tfstate
                path: ./terraform

            - name: Terraform Destroy
              run: terrafom destroy -auto-approve tfstate
